# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Global excludes, override per repo below if different excludes required.
# exclude: >
#   (?x)^(
#     DIRNAME_OR_FILENAME_HERE
#     | DIRNAME_OR_FILENAME_HERE
#     | DIRNAME_OR_FILENAME_HERE
#   )
repos:
  # Note: hooks that add content must run before ones which check formatting, lint, etc
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: insert-license
        language: python
        files: \.py$
        args:
          - --license-filepath
          - license_header/mpl2_header.txt
          - --comment-style
          - "|#|"
      - id: insert-license
        files: \.sh$
        args:
          - --license-filepath
          - license_header/mpl2_header.txt
      - id: insert-license
        files: \.yaml$
        args:
          - --license-filepath
          - license_header/mpl2_header.txt
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: debug-statements
      # - id: check-yaml  # can't be used with pyyaml-env package's !ENV (yet?)
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.3
    hooks:
      - id: ruff
      - id: ruff-format
