# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# NB this workflow needs a cache of HTML documents, emitted by the main
# site-scanning workflow for the CDN origin only

name: Check CDN for geo stability

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  check_geo_from_cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Download page cache
        id: download-page-cache
        uses: actions/download-artifact@v3
        with:
          name: page_cache
          path: page_cache
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Scan the dumped cache for geo-code consistency
        run: python bin/check_for_cdn_geo_consistency.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
