# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: "Robots.txt checking"
on:
  workflow_dispatch:
  schedule:
    - cron: "5 0/3 * * *" # At minute 5 past every 3rd hour from 0 through 23.

env:
  HOSTNAME: ${{ secrets.MOZORG_CDN_HOSTNAME }}

jobs:
  run_robots_txt_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check robots.txt on main CDN
        shell: bash
        run: bin/robots_check.sh
