name: "Scheduled checks" # Note that this name appears in the README's badge
on:
  push:
  # TEMPORARILY DISABLED
  # schedule:
  #   - cron: "15 * * * *"
jobs:
  run_on_cdn:
    runs-on: ubuntu-latest
    name: Check main CDN
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run checker
        run: python bin/run_checks.py --sitemap-url=https://www.mozilla.org/sitemap.xml
      - name: Upload output files
        uses: actions/upload-artifact@v2
        with:
          name: scan-results
          path: output
